services:
  - type: web
    name: avisa
    env: docker
    region: frankfurt
    plan: free
    branch: main
    docker:
      dockerfilePath: ./Dockerfile
    rootDir: frontend
    buildFilter:
      paths:
        - frontend/**
      ignoredPaths:
        - frontend/**/*.spec.ts
    autoDeploy: true
