services:
  - type: web
    name: avisa
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    buildFilter:
      paths:
        - backend/**
        - Dockerfile
        - render.yaml
    healthCheckPath: /api/health
    autoDeploy: true
