CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(255),
    tipo_usuario VARCHAR(20) NOT NULL DEFAULT 'cliente'
        CHECK (tipo_usuario IN ('cliente', 'profesional', 'ambos')),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorias (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE trabajos (
    id_trabajo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'en_proceso', 'completado', 'cancelado')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trabajos_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_trabajos_categoria FOREIGN KEY (id_categoria)
        REFERENCES categorias (id_categoria) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ofertas (
    id_oferta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL CHECK (precio >= 0),
    ubicacion VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo'
        CHECK (estado IN ('activo', 'inactivo', 'pausado')),
    fecha_publicacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ofertas_profesional FOREIGN KEY (id_profesional)
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_ofertas_categoria FOREIGN KEY (id_categoria)
        REFERENCES categorias (id_categoria) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_trabajos_usuario ON trabajos (id_usuario);
CREATE INDEX idx_trabajos_categoria ON trabajos (id_categoria);
CREATE INDEX idx_ofertas_profesional ON ofertas (id_profesional);
CREATE INDEX idx_ofertas_categoria ON ofertas (id_categoria);

INSERT INTO categorias (nombre) VALUES
    ('Diseño web'),
    ('Reformas'),
    ('Fotografía'),
    ('Educación'),
    ('Jardinería'),
    ('Montajes'),
    ('Otros');
