CREATE TABLE sesiones_usuario (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_sesiones_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_sesiones_usuario_usuario ON sesiones_usuario (id_usuario);
CREATE INDEX idx_sesiones_usuario_expiracion ON sesiones_usuario (fecha_expiracion);
