CREATE TABLE propuestas (
    id_propuesta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trabajo BIGINT NOT NULL,
    id_profesional BIGINT NOT NULL,
    mensaje TEXT NOT NULL,
    precio_propuesto NUMERIC(10, 2) NOT NULL CHECK (precio_propuesto > 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'aceptada', 'rechazada')),
    fecha_propuesta TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_propuestas_trabajo FOREIGN KEY (id_trabajo)
        REFERENCES trabajos (id_trabajo) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_propuestas_profesional FOREIGN KEY (id_profesional)
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX uq_propuestas_profesional_pendiente
    ON propuestas (id_trabajo, id_profesional)
    WHERE estado = 'pendiente';

CREATE UNIQUE INDEX uq_propuestas_trabajo_aceptada
    ON propuestas (id_trabajo)
    WHERE estado = 'aceptada';

CREATE INDEX idx_propuestas_profesional ON propuestas (id_profesional, fecha_propuesta DESC);
